metadata:
  timestamp: "2024-08-10T10:30:00Z"
  primary_agent: "main"
  sub_agent: "backend"
  task_id: "user-auth-implementation"
  task_type: "feature_implementation"

task_definition:
  purpose: "ユーザー認証機能の実装"
  background: "セキュアなログインシステムが必要"
  expected_outcome: "JWT認証システムの完全実装"

context:
  related_files:
    - path: "src/models/user.js"
      status: "existing"
      description: "ユーザーモデル定義"
  tech_stack:
    - "Node.js v18"
    - "Express 4.18"
    - "JWT"
  constraints:
    - "bcryptでパスワードハッシュ化必須"
    - "リフレッシュトークン実装必須"
    - "セッション管理はステートレス"
  dependencies:
    - "userモデル定義済み"
    - "データベース接続設定済み"

completion_criteria:
  functional: 
    - "POST /api/auth/login - ログインAPI"
    - "POST /api/auth/logout - ログアウトAPI"
    - "POST /api/auth/refresh - トークンリフレッシュAPI"
  non_functional:
    - "アクセストークン有効期限: 15分"
    - "リフレッシュトークン有効期限: 7日"
    - "パスワード試行回数制限: 5回"
  test:
    - "認証成功・失敗の単体テスト"
    - "トークン期限切れテスト"
    - "不正トークンテスト"