metadata:
  timestamp: "2025-08-10T10:30:00Z"
  primary_agent: "main"
  sub_agent: "go-backend-developer"
  task_id: "go-rest-api-initialization"

task_definition:
  purpose: "新規Go REST APIプロジェクトの初期構造作成"
  background: "指定された技術スタックを使用したClean ArchitectureベースのREST API開発"
  expected_outcome: "プロジェクト基盤となるディレクトリ構成、依存関係設定、基本実装"

context:
  related_files: []
  tech_stack:
    - "Go"
    - "OpenAPI (ogen)"
    - "chi (HTTPルータ)"
    - "wire (DI)"
    - "Clean Architecture"
    - "github.com/sethvargo/go-envconfig (環境変数)"
  constraints:
    - "Clean Architectureの層構造を厳密に守る"
    - "依存関係の注入にはwireを使用"
    - "API仕様はOpenAPIで定義し、ogenで生成"
    - "HTTPルータはchiを使用"
    - "環境変数管理にはgo-envconfigを使用"
  dependencies:
    - "新規プロジェクトのため依存関係なし"

completion_criteria:
  functional:
    - "go.modファイルの作成と依存関係設定"
    - "Clean Architectureに基づくディレクトリ構成"
    - "OpenAPI spec基本構造"
    - "依存性注入設定（wire）"
    - "環境変数設定構造"
    - "基本的なHTTPサーバー起動コード"
  non_functional:
    - "保守性の高いディレクトリ構成"
    - "拡張性を考慮した設計"
  test:
    - "プロジェクトのビルドが成功すること"
    - "基本的なHTTPサーバーが起動すること"

additional_requirements:
  directory_structure_priority: "特によく検討したディレクトリ構成を実装すること"
  clean_architecture_layers:
    - "entities (ドメインエンティティ)"
    - "use_cases (アプリケーションロジック)"
    - "interfaces (外部インターフェース)"
    - "infrastructure (外部システム実装)"